### ISSUE TITLE
unclear where and how to use the generated output

### ISSUE THREAD

**Issue by timaschew** [suiteplus/nsify#4]
So what can I do with the generated file, `output my-schedule.js`?

**Comment by danieljoppi** [comment]
Use your imagination, you can do what you want with this JSON.
Example, you can use this SuiteScript configuration in [nsmockup](https://github.com/suiteplus/nsmockup): 

``` javascript
var script = nsify('my-schedule.js', 'nsmockup')
nsmockup.createSchedule(script, function(){})
```

**Comment by timaschew** [comment]
Okay, it was not clear to my that the generated output can be used in nsmockup at all, nsmockup is not mentioned in the readme.
At least for NetSuite noobs like me was not obvious.

BTW (offtopic): is there a good documentation for dummies how all the script types are working and what's the difference between: suitelet, restlet, schedule, userevent, workflow. And what is a bundle.

**Comment by danieljoppi** [comment]
the project was not finished ... but thanks for your consideration

I will create some tutorial in next release ... (I hope ehehehe :+1: )

:star2: I need more time to finish the documentation
